// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Course
{
    public int CourseID { get; set; }

    public string CourseName { get; set; }

    public string Subject { get; set; }

    public string PreReq { get; set; }

    public string Book { get; set; }
}