// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Room
{
    public int RoomID { get; set; }

    public int? Capasity { get; set; }

    public int? Floor { get; set; }

    public string RoomType { get; set; }
}